name: Deploy
on:
  push:
    branches: 'main'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Rebuild & restart containers on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: cd ~/epidemic-simulator && git fetch origin main && git reset --hard origin/main && systemctl restart bokeh-epidemisim
